use_frameworks!

platform :ios, '10.0'

target 'CustomAlertDialog_Example' do
  pod 'CustomAlertDialog', :path => '../'

  target 'CustomAlertDialog_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
